code --install-extension alexandreramos.vulgocode-color-theme --force
code --install-extension bierner.markdown-checkbox --force
code --install-extension bierner.markdown-mermaid --force
code --install-extension cucumberopen.cucumber-official --force
code --install-extension davidanson.vscode-markdownlint --force
code --install-extension dotjoshjohnson.xml --force
code --install-extension druideinformatique.antidote --force
code --install-extension firefox-devtools.vscode-firefox-debug --force
code --install-extension github.copilot --force
code --install-extension github.copilot-chat --force
code --install-extension hashhar.gitattributes --force
code --install-extension kisstkondoros.vscode-codemetrics --force
code --install-extension mathematic.vscode-latex --force
code --install-extension ms-azure-devops.azure-pipelines --force
code --install-extension ms-azuretools.azure-dev --force
code --install-extension ms-azuretools.vscode-azureappservice --force
code --install-extension ms-azuretools.vscode-azurecontainerapps --force
code --install-extension ms-azuretools.vscode-azureresourcegroups --force
code --install-extension ms-azuretools.vscode-azurefunctions 
code --install-extension ms-azuretools.vscode-azureresourcegroups --force
code --install-extension ms-azuretools.vscode-azurestaticwebapps --force
code --install-extension ms-azuretools.vscode-azurestorage --force
code --install-extension ms-azuretools.vscode-azurevirtualmachines --force
code --install-extension ms-azuretools.vscode-bicep --force
code --install-extension ms-azuretools.vscode-cosmosdb --force
code --install-extension ms-azuretools.vscode-docker --force
code --install-extension ms-dotnettools.csharp --force
code --install-extension ms-dotnettools.vscode-dotnet-runtime --force
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-wsl --force
code --install-extension ms-vscode.azure-account --force
code --install-extension ms-vscode.powershell --force
code --install-extension ms-vscode.vscode-node-azure-pack --force
code --install-extension pascalreitermann93.vscode-yaml-sort --force
code --install-extension pkief.material-icon-theme --force
code --install-extension streetsidesoftware.code-spell-checker --force
code --install-extension streetsidesoftware.code-spell-checker-french --force
code --install-extension visualstudioexptteam.intellicode-api-usage-examples --force
code --install-extension visualstudioexptteam.vscodeintellicode --force
code --install-extension vscode-icons-team.vscode-icons --force